### ISSUE TITLE
font dir is more static than README.md makes you believe

### ISSUE THREAD

**Issue by TimB87** [glacambre/nwin#10]
Hi!

`$HOME/downloads/NotoSansMono` actually points statically to `/home/me/downloads/NotoSansMono`, not `$HOME`, it won't start with `$HOME/downloads/NotoSansMono`.

**Comment by glacambre** [comment]
Ha, true! Thank you for reporting that (and congratulations for probably being the first person to look at nwin's code/attempt to run it! ;) ).
